### ISSUE TITLE
How do i create my own server

### ISSUE THREAD

**Issue by 0rShemesh** [ide-stories/vscode-stories#66] opened 2020-11-02 19:13 UTC
Hey, 
I very liked your idea!!!!!

@takashi1kun explained what i want to create
> I think he wants to create its own private self-hosted instance of the stories server, so that the GIFs are not uploaded to your azure server but to one of their local servers and they can only see stories of other devs on their local network.
> I think that way of using the extension can actually be useful beyond being a meme and can work as another tool for team-work in a dev team, especially because in business environments you usually can't just share your code over the internet legally speaking but there would be no problem in sharing it with one of your coworkers and it may even be useful to show how you finally solved "that bug" to your coworkers.

### Thanks!

**Comment by benawad** [comment] 2020-11-03 02:12
What?

**Comment by takashi1kun** [comment] 2020-11-03 08:55
> What?

I think he wants to create its own private self-hosted instance of the stories server that the gif is not uploaded to your azure server but to one of their local servers and they can only see stories on their local network.
I think that way of using the extension can actually be useful as another tool for team-work in a dev team, especially because in business environments you usually can't just share your code over the internet legally speaking but there would be no problem in sharing it with one of your coworkers and it may even be useful.

**Comment by DavidVu96** [comment] 2020-11-03 20:30
you run your local server of https://github.com/benawad/vscode-stories-api
then in line 13 of src/query.ts, change the url to your local server

**Comment by 0rShemesh** [comment] 2020-11-05 21:57
> > What?
> 
> I think he wants to create its own private self-hosted instance of the stories server, so that the GIFs are not uploaded to your azure server but to one of their local servers and they can only see stories of other devs on their local network.
> I think that way of using the extension can actually be useful beyond being a meme and can work as another tool for team-work in a dev team, especially because in business environments you usually can't just share your code over the internet legally speaking but there would be no problem in sharing it with one of your coworkers and it may even be useful to show how you finally solved "that bug" to your coworkers.

@benawad
i think your idea is amazing for team work in dev team!

**Comment by stemount** [comment] 2020-11-06 11:24
@0rShemesh @DavidVu96 @takashi1kun @benawad 

This is a compliment, an idea and also just the "technical how-to" of how to do this:

- What is the implementation for deploying as this has an API and a serverless action for the image upload?
  - Would your "company" want to deploy CloudFormation or similar templates to this
  - One huge downside I see here is having multiple versions of VS Stories on here
  - It'd be good to use `benawad.stories` on the VS Code extensions store instead of creating horrible clones and using VS Code extensions settings and environment variables in the API and Serverless image uploader.
- How popular would this feature request really be outside of your team @0rShemesh?

**Comment by benawad** [comment] 2020-11-06 14:08
I could add a setting that lets you change the api endpoint, so you can keep the same extension.

**Comment by TheFern2** [comment] 2021-02-01 16:33
@bar9 are we good to go to add server url for user configuration?

**Comment by TheFern2** [comment] 2021-02-01 16:40
Also this is duplicate of #53 closing and leaving that one open.

**Closed by TheFern2** 2021-02-01 16:40 UTC
