### ISSUE TITLE
Missing autocompleted characters

### ISSUE THREAD

**Issue by krissdap** [ide-stories/vscode-stories#86] opened 2020-11-17 08:17 UTC
Recorded story missed autocompleted closing parentheses.

Version: 2.21.0
OS: MacOS 10.15.7
VS Code: 1.51.1

<img width="525" alt="stories-actual" src="https://user-images.githubusercontent.com/5546755/99363518-6dd27e80-28e7-11eb-8efc-37bde9b8e88f.png">
<img width="281" alt="stories-recorded" src="https://user-images.githubusercontent.com/5546755/99363524-70cd6f00-28e7-11eb-95df-fabe478e557c.png">

**Comment by bar9** [comment] 2020-11-25 05:26
Thanks for reporting this with a screenshot, appreciate the clarity.
Duplicate of #90

**Closed by bar9** 2020-11-25 05:26 UTC
Labels: duplicate
